# Generated by Django 3.2 on 2022-04-25 21:21

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220425_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo_url',
            field=models.ImageField(upload_to=main.utils.upload_image),
        ),
    ]
