# Generated by Django 3.2 on 2022-04-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_gallery_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='s3_url',
            field=models.CharField(default='https://photomarble.s3.ap-northeast-2.amazonaws.com/', max_length=400),
            preserve_default=False,
        ),
    ]
