# Generated by Django 3.2 on 2022-04-25 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220425_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='like_users',
            field=models.ManyToManyField(related_name='like_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
