# Generated by Django 3.2 on 2022-04-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_gallery_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='../static/main/images/balnk-profile.png', upload_to='profile'),
        ),
    ]
