# Generated by Django 3.2 on 2022-04-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo_url',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
