# Generated by Django 3.2 on 2022-04-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_gallery_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_s3_url',
            field=models.CharField(default='https://photomarble.s3.ap-northeast-2.amazonaws.com/profile/blank-profile.png', max_length=400),
        ),
    ]
