# Generated by Django 3.2 on 2022-05-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_gallery_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Free',
        ),
        migrations.AddField(
            model_name='collection',
            name='s3_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
